### ISSUE TITLE
Is supporting CSS `font-variant-numeric: tabular-nums;` feasible?

### ISSUE THREAD

**Issue by yuriy-sng** [NDISCOVER/Exo-2.0#9]
I'd like to have the option to align the numbers by making them all have the same width.

![image](https://user-images.githubusercontent.com/60257988/86746873-a9a52f80-c03b-11ea-801a-24622c6ede14.png)

Is is feasible/technically possible to add this feature to the font? 

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

**Comment by NDISCOVER** [comment]
The feature is already in the font. It is an opentype feature: tabular lining figures. You just need to activate those features via CSS. I don't know how it is done, but I know it is possible.

**Comment by yuriy-sng** [comment]
You're right, I was using Google Fonts which appears to not have support for this ATM. Thanks!
